---

language: bash

addons:
  apt:
    packages:
      - coreutils

env:
  - SHUNIT_COLOR=always

matrix:
  include:
    - script:
        - bash test/test_bright-apis.bash
    - script:
        - shellcheck -x bright.bash
